<?php

    $posts = $this->getPosts($this->getRequest()->getParam('category'));
    $category = $this->getCategory($this->getRequest()->getParam('category'));

?>

<div class="<?= $this->getData('class')?>">
    <div class="<?= $this->getData('class')?>">
        <?= $category['name'] ?>
    </div>
    <div class="<?= $this->getData('class')?>">
        <?= $category['description'] ?>
    </div>
    <div class="<?= $this->getData('class')?>">
        <?= $category['image'] ?>
    </div>

</div>

<ul class="<?= $this->getData('class')?>">
    <?php foreach ($posts as $post):?>
            <li class="<?= $this->getData('class')?>"><a href="<?=Mage::getUrl('blog/post/view?id='.$post->getPostIds()) ?>"><?= $this->getPostNameById($post->getPostIds()) ?></a></li>
    <?php endforeach ?>
</ul>


